import { ClerkProvider } from "@clerk/nextjs";
import { Header } from "./_components/Header";
import "./globals.css";
import { Suspense } from "react";
import { StepProvider } from "./become-freelancer/_components/Provider";
import { Toaster } from "@/components/ui/sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <Suspense>
        <html lang="en">
          <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
          >
            <StepProvider>{children}</StepProvider>
            <Toaster />
          </body>
        </html>
      </Suspense>
    </ClerkProvider>
  );
}
